# Introduction
We will use this notebook to explore the data initially, before initiating any trading algorithm.

# Import

In [1]:
# Standard library imports
import datetime as dt
import os

# Third party imports
import pandas as pd
import numpy as np

/Users/mihneapiuaru/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

# Data Analysis

In [2]:
df_train = pd.read_csv('df_train.csv')

In [7]:
df_train.head()

         date symbol   open  close    low   high     volume
0  2010-01-04   ACTS  15.13  14.97  14.84  15.28   5459.882
1  2010-01-04   AMWD   7.00   7.12   6.98   7.14  92067.275
2  2010-01-04    ARV  18.27  18.31  18.12  18.47  38034.257
3  2010-01-04    BBY   3.11   3.11   3.09   3.13  40964.820
4  2010-01-04   BCDM  19.78  19.53  19.41  19.90   3646.991

In [8]:
df_train.tail()

              date symbol   open  close    low   high     volume
100595  2013-12-31    XTG  29.17  28.62  28.99  28.98  42044.703
100596  2013-12-31    YPN  13.88  13.85  13.80  13.96  29030.106
100597  2013-12-31    YRD  11.68  11.57  11.66  11.66  11778.336
100598  2013-12-31   YVNL   2.43   2.40   2.42   2.41   6431.843
100599  2013-12-31    ZQN  21.16  21.42  21.13  21.49  54319.469

In [4]:
df_train.shape

(100600, 7)

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100600 entries, 0 to 100599
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    100600 non-null  object
 1   symbol  100600 non-null  object
 2   open    100600 non-null  float64
 3   close   100600 non-null  float64
 4   low     100600 non-null  float64
 5   high    100600 non-null  float64
 6   volume  100600 non-null  float64
dtypes: float64(5), object(2)
memory usage: 5.4+ MB

In [13]:
print('Number of unique symbols:', len(df_train['symbol'].unique()))
print('Number of unique dates:', len(df_train['date'].unique()))

Number of unique symbols: 100
Number of unique dates: 1006

In [14]:
df_train.describe()

,open,close,low,high,volume
count,100600.000000,100600.000000,100600.000000,100600.000000,1.006000e+05
mean,21.720677,20.363524,20.618948,20.917851,6.660785e+04
std,20.064846,19.852803,18.998291,19.099819,1.057868e+05
min,1.190000,1.100000,1.120000,1.160000,5.868770e+02
25%,7.200000,6.650000,6.890000,6.950000,1.459317e+04
50%,15.090000,13.810000,14.290000,14.690000,3.323060e+04
75%,29.060000,27.300000,28.280000,28.740000,7.313989e+04
max,184.300000,212.430000,182.880000,185.810000,2.990820e+06