# Introduction
We will use this notebook to explore the data initially, before initiating any trading algorithm.

# Import

In [36]:
# Standard library imports
import datetime as dt
import os

# Third party imports
import pandas as pd
import polars as pl
import numpy as np
import matplotlib.pyplot as plt

# Data Analysis

In [37]:
df_train = pd.read_csv('df_train.csv')

In [38]:
df_train.head()

         date symbol   open  close    low   high     volume
0  2010-01-04   ACTS  15.13  14.97  14.84  15.28   5459.882
1  2010-01-04   AMWD   7.00   7.12   6.98   7.14  92067.275
2  2010-01-04    ARV  18.27  18.31  18.12  18.47  38034.257
3  2010-01-04    BBY   3.11   3.11   3.09   3.13  40964.820
4  2010-01-04   BCDM  19.78  19.53  19.41  19.90   3646.991

In [39]:
df_train.tail()

              date symbol   open  close    low   high     volume
100595  2013-12-31    XTG  20.15  20.00  20.15  20.15  42044.703
100596  2013-12-31    YPN  14.94  14.82  14.94  14.94  29030.106
100597  2013-12-31    YRD   3.40   3.39   3.40   3.40  11778.336
100598  2013-12-31   YVNL   4.25   4.24   4.25   4.25   6431.843
100599  2013-12-31    ZQN  32.01  32.04  32.01  32.01  54319.469

In [40]:
df_train.shape

(100600, 7)

In [41]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100600 entries, 0 to 100599
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    100600 non-null  object
 1   symbol  100600 non-null  object
 2   open    100600 non-null  float64
 3   close   100600 non-null  float64
 4   low     100600 non-null  float64
 5   high    100600 non-null  float64
 6   volume  100600 non-null  float64
dtypes: float64(5), object(2)
memory usage: 5.4+ MB

In [42]:
# Unique symbols
print('Number of unique symbols:', len(df_train['symbol'].unique()))
print('Number of unique dates:', len(df_train['date'].unique()))

Number of unique symbols: 100
Number of unique dates: 1006